version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: WordPress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - wp-network

  wordpress:
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: WordPress
    networks:
      - wp-network

networks:
  wp-network:

volumes:
  wordpress_data:


  